package org.usfirst.frc.team5407.robot;

import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {

	// Winch
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static AnalogPotentiometer winchPotentiometer;
    public static SpeedController winchVictor;
//    public static DigitalInput winchLimitTop;
    public static DigitalInput clawLimitRetract;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Arm
	public static final double armSpeed = 1.0;

	// Compressor
	public static final int DIO_Compressor = 1;
	public static final int Relay_Compressor = 1;

	// Chassis
	public static final int Solenoid_Gear_Shift = 1;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        winchPotentiometer = new AnalogPotentiometer(0, 1.0, 0.0);
        LiveWindow.addSensor("Winch", "Potentiometer", winchPotentiometer);
        
        winchVictor = new VictorSP(2);
        LiveWindow.addActuator("Winch", "Victor", (VictorSP) winchVictor);
        
//        winchLimitTop = new DigitalInput(0);
//        LiveWindow.addSensor("Winch", "winchLimitTop", winchLimitTop);
        
        clawLimitRetract = new DigitalInput(1);
        LiveWindow.addSensor("Claw", "clawLimitRetract", clawLimitRetract);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}

